import * as functions from "firebase-functions/v2/https";
import * as admin from "firebase-admin";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const PLAY_STORE_URL = "https://play.google.com/store/apps/details?id=com.swiftshop.client";
// FIX (2026-09-22): this was hardcoded to the DEV project (swift-dev-3d3ae),
// meaning every smart link generated by this function pointed at dev, not
// production, regardless of which project the function itself was deployed to.
const SITE_ORIGIN = "https://swift-d1baa.web.app";

function renderPage(opts: {
  title: string;
  description: string;
  imageUrl: string;
  pageUrl: string;
  deepLink: string | null;
  listingId: string | null;
  priceDisplay: string | null;
  inStock: boolean;
}): string {
  const { title, description, imageUrl, pageUrl, deepLink, listingId, priceDisplay, inStock } = opts;
  const safeTitle = escapeHtml(title);
  const safeDescription = escapeHtml(description);
  const safeImage = escapeHtml(imageUrl);
  const safeUrl = escapeHtml(pageUrl);

  // Real Add to Cart / Buy Now buttons only render when we have a real listing
  // (i.e. not on the 404/error fallback pages). They call into the same
  // app.js the rest of the site uses, so cart state and checkout are shared
  // with the browse/shop pages — this page is not a separate mini-app.
  const commerceButtons = listingId ? `
  <div class="price">${priceDisplay ? escapeHtml(priceDisplay) : ""}</div>
  <div class="actions">
    <button class="btn secondary" id="addCartBtn" ${inStock ? "" : "disabled"}>Add to Cart</button>
    <button class="btn primary" id="buyNowBtn" ${inStock ? "" : "disabled"}>Buy Now</button>
  </div>
  ${!inStock ? '<p class="oos">Out of stock</p>' : ""}
  ` : "";

  const commerceScript = listingId ? `
  <script type="module">
    import { addToCart } from "/app.js";
    const id = ${JSON.stringify(listingId)};
    const title = ${JSON.stringify(title)};
    document.getElementById("addCartBtn")?.addEventListener("click", (e) => {
      addToCart(id, title, 1);
      e.target.textContent = "Added \u2713";
    });
    document.getElementById("buyNowBtn")?.addEventListener("click", () => {
      addToCart(id, title, 1);
      window.location.href = "/checkout";
    });
  </script>` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${safeTitle} — SwiftShop</title>
  <meta property="og:title" content="${safeTitle}">
  <meta property="og:description" content="${safeDescription}">
  <meta property="og:image" content="${safeImage}">
  <meta property="og:url" content="${safeUrl}">
  <meta property="og:type" content="product">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${safeTitle}">
  <meta name="twitter:description" content="${safeDescription}">
  <meta name="twitter:image" content="${safeImage}">
  <style>
    body { font-family: -apple-system, Roboto, sans-serif; max-width: 480px; margin: 40px auto; padding: 0 20px; text-align: center; color: #1a1a1a; }
    img { width: 100%; max-width: 320px; border-radius: 12px; margin-bottom: 20px; }
    h1 { font-size: 20px; margin: 0 0 8px; }
    p { color: #555; margin: 0 0 24px; }
    .price { font-size: 18px; font-weight: 700; color: #1b6ef3; margin-bottom: 16px; }
    .actions { display: flex; gap: 10px; margin-bottom: 20px; }
    .btn { flex: 1; padding: 14px; border-radius: 10px; border: none; font-weight: 600; font-size: 15px; cursor: pointer; }
    .btn.primary { background: #1b6ef3; color: white; }
    .btn.secondary { background: #eee; color: #1a1a1a; }
    .btn:disabled { opacity: 0.5; cursor: not-allowed; }
    a.btn { display: block; text-decoration: none; margin-bottom: 12px; }
    a.btn.primary { background: #1b6ef3; color: white; }
    a.btn.secondary { background: #eee; color: #1a1a1a; }
    .oos { color: #c00; font-size: 13px; margin-top: -10px; }
  </style>
</head>
<body>
  ${safeImage ? `<img src="${safeImage}" alt="${safeTitle}">` : ""}
  <h1>${safeTitle}</h1>
  <p>${safeDescription}</p>
  ${commerceButtons}
  ${deepLink ? `<a class="btn secondary" href="${escapeHtml(deepLink)}">Open in SwiftShop app</a>` : ""}
  <a class="btn secondary" href="${PLAY_STORE_URL}">Get the SwiftShop app</a>
  ${commerceScript}
</body>
</html>`;
}

export const renderListingPreview = functions.onRequest(async (req, res) => {
  const match = req.path.match(/\/listing\/([^/]+)/);
  const listingId = match ? match[1] : null;

  if (!listingId) {
    res.status(404).send(renderPage({
      title: "SwiftShop",
      description: "Buy and sell in Maseru",
      imageUrl: "",
      pageUrl: SITE_ORIGIN,
      deepLink: null,
      listingId: null,
      priceDisplay: null,
      inStock: false
    }));
    return;
  }

  try {
    const doc = await admin.firestore().collection("listings").doc(listingId).get();
    if (!doc.exists) {
      res.status(404).send(renderPage({
        title: "Listing not found",
        description: "This listing may have been removed.",
        imageUrl: "",
        pageUrl: `${SITE_ORIGIN}/listing/${listingId}`,
        deepLink: null,
        listingId: null,
        priceDisplay: null,
        inStock: false
      }));
      return;
    }

    const data = doc.data()!;
    const title: string = data.title || "SwiftShop Listing";
    const description: string = data.description || "Check this out on SwiftShop";
    const imageUrl: string = (data.imageUrls && data.imageUrls[0]) || "";
    const priceMinorUnits: number = data.priceMinorUnits || 0;
    const priceCurrency: string = data.priceCurrency || "LSL";
    const priceDisplay = `${priceCurrency} ${(priceMinorUnits / 100).toFixed(2)}`;
    const inStock = (data.isAvailable === true) && ((data.stockQuantity || 0) > 0);

    res.status(200).send(renderPage({
      title: `${title} — ${priceDisplay}`,
      description,
      imageUrl,
      pageUrl: `${SITE_ORIGIN}/listing/${listingId}`,
      deepLink: `swiftshop://listing/${listingId}`,
      listingId,
      priceDisplay,
      inStock
    }));
  } catch (err) {
    res.status(500).send(renderPage({
      title: "SwiftShop",
      description: "Something went wrong loading this listing.",
      imageUrl: "",
      pageUrl: SITE_ORIGIN,
      deepLink: null,
      listingId: null,
      priceDisplay: null,
      inStock: false
    }));
  }
});

export const renderShopPreview = functions.onRequest(async (req, res) => {
  const match = req.path.match(/\/shop\/([^/]+)/);
  const shopId = match ? match[1] : null;

  if (!shopId) {
    res.status(404).send(renderPage({
      title: "SwiftShop",
      description: "Buy and sell in Maseru",
      imageUrl: "",
      pageUrl: SITE_ORIGIN,
      deepLink: null,
      listingId: null,
      priceDisplay: null,
      inStock: false
    }));
    return;
  }

  try {
    const doc = await admin.firestore().collection("shops").doc(shopId).get();
    if (!doc.exists) {
      res.status(404).send(renderPage({
        title: "Shop not found",
        description: "This shop may have been removed.",
        imageUrl: "",
        pageUrl: `${SITE_ORIGIN}/shop/${shopId}`,
        deepLink: null,
        listingId: null,
        priceDisplay: null,
        inStock: false
      }));
      return;
    }

    const data = doc.data()!;
    const name: string = data.name || "SwiftShop Shop";
    const description: string = data.description || "Check out this shop on SwiftShop";
    const imageUrl: string = data.coverUrl || data.logoUrl || "";

    res.status(200).send(renderPage({
      title: name,
      description,
      imageUrl,
      pageUrl: `${SITE_ORIGIN}/shop/${shopId}`,
      deepLink: `swiftshop://shop/${shopId}`,
      listingId: null,
      priceDisplay: null,
      inStock: false
    }));
  } catch (err) {
    res.status(500).send(renderPage({
      title: "SwiftShop",
      description: "Something went wrong loading this shop.",
      imageUrl: "",
      pageUrl: SITE_ORIGIN,
      deepLink: null,
      listingId: null,
      priceDisplay: null,
      inStock: false
    }));
  }
});
